{
 "title": "AI System Health",
 "time": { "from": "2026-01-30T18:18:00.642Z", "to": "2026-01-30T22:18:00.642Z" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests: Success vs Failure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "requests_success_total", "legendFormat": "__auto" },
    { "expr": "requests_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(request_latency_ms_bucket[5m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}